SELECT EXTENSION, * FROM dbo.ADFUNC WHERE FUNCTION_CODE='SAMFLM'


SELECT * FROM dbo.ADFUNC WHERE FUNCTION_CODE='ICIMSR'


UPDATE ADFUNC SET EXTENSION='STD:Inventory:InventoryMovement/Adjustment'
WHERE FUNCTION_CODE='ICIMSA'


UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Location' WHERE FUNCTION_CODE='SAMFLM'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Port' WHERE FUNCTION_CODE='SAMFPT'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Item' WHERE FUNCTION_CODE='SAMFID'


UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Color' WHERE FUNCTION_CODE='SAMFCO'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Size' WHERE FUNCTION_CODE='SAMFSZ'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Unit' WHERE FUNCTION_CODE='SAMFUM'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Item' WHERE FUNCTION_CODE='SAMFIM'


UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Customer' WHERE FUNCTION_CODE='SAMFCM'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Salesman' WHERE FUNCTION_CODE='SAMFSM'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Vendor' WHERE FUNCTION_CODE='SAMFVM'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Buyer' WHERE FUNCTION_CODE='SAMFBM'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:ChargeType' WHERE FUNCTION_CODE='SAMFSC'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Currency' WHERE FUNCTION_CODE='SAMFCU'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Collection' WHERE FUNCTION_CODE='SAMFCL'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:AttachmentFileType' WHERE FUNCTION_CODE='SAMFFT'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:ReasonCode' WHERE FUNCTION_CODE='SAMFRC'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Account' WHERE FUNCTION_CODE='SAMFAM'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:SAMFFM' WHERE FUNCTION_CODE='FundCode'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:PayTerm' WHERE FUNCTION_CODE='SAMFPM'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Style' WHERE FUNCTION_CODE='SAMFSY'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:WorkCentre' WHERE FUNCTION_CODE='PRPNWC'




UPDATE dbo.ADFUNC SET EXTENSION='STD:Document:Attachment' WHERE FUNCTION_CODE='SAMFAB'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Document:ShipViaCode' WHERE FUNCTION_CODE='SAMFSV'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Document:Panel' WHERE FUNCTION_CODE='SAMFPN'



UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Item/Approval' WHERE FUNCTION_CODE='SAMFIA'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Vendor/Approval' WHERE FUNCTION_CODE='SAMFVA'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:Customer/Approval' WHERE FUNCTION_CODE='SAMFCA'




UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:TextType' WHERE FUNCTION_CODE='SAOSTT'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:CustomerGroup' WHERE FUNCTION_CODE='SAGCCG'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:ItemGroup' WHERE FUNCTION_CODE='SAGCIG'
UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:VendorGroup' WHERE FUNCTION_CODE='SAGCVG'

UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:JobCategory' WHERE FUNCTION_CODE='SAGCJC'

UPDATE dbo.ADFUNC SET EXTENSION='STD:Administration:Translation' WHERE FUNCTION_CODE='SALMLM'


UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:VoucherType' WHERE FUNCTION_CODE='SAINVT'

UPDATE dbo.ADFUNC SET EXTENSION='STD:Administration:User' WHERE FUNCTION_CODE='SAUMUR'


UPDATE dbo.ADFUNC SET EXTENSION='STD:Administration:Company' WHERE FUNCTION_CODE='SAUTCB'


UPDATE dbo.ADFUNC SET EXTENSION='STD:MasterData:CompanyParameter' WHERE FUNCTION_CODE='SAUTBP'



SELECT * FROM dbo.ADMNUI  规条制度
SELECT * FROM dbo.ADMNUB  图片

SELECT * FROM dbo.ADUGRP 用户组别

功能
SELECT * FROM dbo.ADFUNC 


----------------------------------------------------------------------------------------------
SELECT * FROM dbo.UserLog
SELECT * FROM dbo.UserLogDetail
SELECT * FROM dbo.UserLogDetailAction



SAGCAN	Analysis Codes

SAGCIC	Inspection Codes Maintenance
SAGCAT	Customer Address Types
SAGCCT	Customer Contact Types
SAGCLT	Customer Link Types
SAMFPK	Packaging Types
	
SAMFPL	Packing Label Template
SAINES	Evaluation STANDARD

SELECT * FROM dbo.ADMNUD WHERE USER_GROUP='fcs' AND PROCESS_CODE='SYS01' AND MENU_TYPE='CLAS'

PRPEBA	BOM Approval


SAMFCR	Contractor Master
SAMFCP	Contractor Payment Terms
SAUTPS	Job Position Maintenance
SAMFCT	Container Maintenance
SAMFST	Shipment Terms Maintenance
	
SAMFBD	Brand Maintenance
SAMFGP	Garment Part Maintenance
SAMFSL	Plastics Material
	
SAMFMM	Item Image Maintenance
SAMFIU	Item-Based Unit Conversion Maintenance
ICIRIS	Item No. Segment Definition
SAMFBS	Bin Segment
SAMFTP	Order Tracker Grouping Maintenance
SAMFTL	Test Lab Master
SAMFTR	Item Test Report Entry



