--sales  
UPDATE dbo.ADFUNC SET EXTENSION='STD:Sales:Quotation'  WHERE FUNCTION_CODE='SLSOSQ'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Sales:SalesOrder'  WHERE FUNCTION_CODE='SLSOSO'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Sales:Shipment'  WHERE FUNCTION_CODE='SLSHSE'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Sales:SalesReturn'  WHERE FUNCTION_CODE='SLSHSR'


--purchasing
UPDATE dbo.ADFUNC SET EXTENSION='STD:Purchasing:PurchaseRequisition'  WHERE FUNCTION_CODE='PUPORE'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Purchasing:PurchaseOrder'  WHERE FUNCTION_CODE='PUPOOE'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Purchasing:Grn'  WHERE FUNCTION_CODE='PUGRRE'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Purchasing:PurchaseReturn'  WHERE FUNCTION_CODE='PUGRRT'

--inventory
UPDATE dbo.ADFUNC SET EXTENSION='STD:Inventory:InventoryMovement/Receipt'  WHERE FUNCTION_CODE='ICIMSR'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Inventory:InventoryMovement/Issue'  WHERE FUNCTION_CODE='ICIMSI'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Inventory:InventoryMovement/Transfer'  WHERE FUNCTION_CODE='ICIMST'
UPDATE dbo.ADFUNC SET EXTENSION='STD:Inventory:InventoryAdjustment'  WHERE FUNCTION_CODE='ICIMSA'


--general ledger
UPDATE dbo.ADFUNC SET EXTENSION='STD:Finance:Voucher'  WHERE FUNCTION_CODE='GLTRVP'

UPDATE dbo.ADFUNC SET EXTENSION='STD:Production:JobOrder'  WHERE FUNCTION_CODE='PRPMJE'


