#region Enterprise Solution
// Copyright © 2006-2018 Enterprise Solution Limited
// Solution:  Enterprise Solution
// Project:   Enterprise Edition/Application
// File:  CompanyParameterColumns.cs
// Date: 2018/04/03 20:51

#endregion

namespace Matrix.Basic.Columns
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;

    [ColumnsScript("Basic.CompanyParameter")]
    [BasedOnRow(typeof(Entities.CompanyParameterRow))]
    public class CompanyParameterColumns
    {
        [EditLink, DisplayName("Db.Shared.RecordId"), AlignRight]
        public Decimal Recnum { get; set; }
        [EditLink]
        public String CompanyName { get; set; }
        public String Address { get; set; }
        public String Address2 { get; set; }
        public String Address3 { get; set; }
        public String Address4 { get; set; }
        public String PostCode { get; set; }
        public String TelNo { get; set; }
        public String FaxNo { get; set; }
        public String Email { get; set; }
        public String TaxAcctNo { get; set; }
        public String BusRegNo { get; set; }
        public DateTime DrevisedDate { get; set; }
        public String DrevisedBy { get; set; }
        public String BranchNo { get; set; }
        public String BaseCurrency { get; set; }
        public Decimal NoOfPeriods { get; set; }
        public String CurrentPeriod { get; set; }
        public String OpenPrdFrom { get; set; }
        public String OpenPrdTo { get; set; }
        public String AllowEntries { get; set; }
        public String AcctRetEarn { get; set; }
        public String AcctCurEarn { get; set; }
        public String AcctEndBs { get; set; }
        public String LocReceiving { get; set; }
        public String LocShipment { get; set; }
        public String LocPos { get; set; }
        public String LocMaterial { get; set; }
        public String LocProduce { get; set; }
        public String IcRevaluation { get; set; }
        public String FgStdCosting { get; set; }
        public String AllocMethod { get; set; }
        public String CostingMethod { get; set; }
        public String AllowLotOpt { get; set; }
        public String PmntFundCode { get; set; }
        public String RcptFundCode { get; set; }
        public String SalesPayTerms { get; set; }
        public String PurchPayTerms { get; set; }
        public String ItemGroup { get; set; }
        public String CustomerGroup { get; set; }
        public String VendorGroup { get; set; }
        public String SlCgtaxCode { get; set; }
        public String SlCltaxCode { get; set; }
        public String SlVgtaxCode { get; set; }
        public String SlVltaxCode { get; set; }
        public String SlItaxCode { get; set; }
        public String PuCgtaxCode { get; set; }
        public String PuCltaxCode { get; set; }
        public String PuVgtaxCode { get; set; }
        public String PuVltaxCode { get; set; }
        public String PuItaxCode { get; set; }
        public String WithTaxation { get; set; }
        public String ProcSalesGtax { get; set; }
        public String ProcSalesLtax { get; set; }
        public String ProcPurchGtax { get; set; }
        public String ProcPurchLtax { get; set; }
        public DateTime TrevisedDate { get; set; }
        public String TrevisedBy { get; set; }
        public DateTime RevisedDate { get; set; }
        public String RevisedBy { get; set; }
        public String AltName { get; set; }
        public String AltAddress { get; set; }
        public String AltAddress2 { get; set; }
        public String AltAddress3 { get; set; }
        public String AltAddress4 { get; set; }
        public String MainBranPath { get; set; }
        public Decimal MainBranCount { get; set; }
        public String OnlineBranUpd { get; set; }
        public String WithCostCtr { get; set; }
        public String WithDept { get; set; }
        public String WithBinCtrl { get; set; }
        public String WithInspection { get; set; }
        public String AcctItmAsset { get; set; }
        public String AcctItmWip { get; set; }
        public String AcctItmConsum { get; set; }
        public String AcctItmScrap { get; set; }
        public String AcctItmPvar { get; set; }
        public String AcctItmReval { get; set; }
        public String AcctItmVaria { get; set; }
        public String AcctItmSales { get; set; }
        public String AcctItmSlret { get; set; }
        public String AcctItmSldisc { get; set; }
        public String AcctItmCogs { get; set; }
        public String AcctItmPurch { get; set; }
        public String AcctItmPuret { get; set; }
        public String AcctItmPudisc { get; set; }
        public String AcctItmPutax { get; set; }
        public String AcctMvtIssue { get; set; }
        public String AcctMvtRcpt { get; set; }
        public String AcctMvtAdj { get; set; }
        public String AcctSlsMisc { get; set; }
        public String AcctSlsMscret { get; set; }
        public String AcctSlsTrdisc { get; set; }
        public String AcctSlsLntax { get; set; }
        public String AcctSlsGrtax { get; set; }
        public String AcctPurMisc { get; set; }
        public String AcctPurMscret { get; set; }
        public String AcctPurTrdisc { get; set; }
        public String AcctPurGrtax { get; set; }
        public String AcctArCash { get; set; }
        public String AcctArCust { get; set; }
        public String AcctArDisc { get; set; }
        public String AcctArAdj { get; set; }
        public String AcctArForex { get; set; }
        public String AcctApCash { get; set; }
        public String AcctApVend { get; set; }
        public String AcctApDisc { get; set; }
        public String AcctApAdj { get; set; }
        public String AcctApForex { get; set; }
        public String AcctApVaria { get; set; }
        public String AcctMachine { get; set; }
        public String AcctEnergy { get; set; }
        public String AcctWater { get; set; }
        public String AcctRental { get; set; }
        public String AcctLabor { get; set; }
        public String AcctInlab { get; set; }
        public String AcctInmat { get; set; }
        public String AcctMisc { get; set; }
        public String AcctSuspAr { get; set; }
        public String AcctSuspAp { get; set; }
        public String AcctSuspIc { get; set; }
        public String AcctSuspPr { get; set; }
        public String AcctSuspFa { get; set; }
        public String AcctSuspSub { get; set; }
        public String AcctSuspIncom { get; set; }
        public String AcctSuspExpen { get; set; }
        public DateTime ArevisedDate { get; set; }
        public String ArevisedBy { get; set; }
        public DateTime BrevisedDate { get; set; }
        public String BrevisedBy { get; set; }
        public String DeptProd { get; set; }
        public String DeptSales { get; set; }
        public String DeptPurch { get; set; }
        public Decimal NoOfShift { get; set; }
        public Decimal Shift1Hrs { get; set; }
        public Decimal Shift2Hrs { get; set; }
        public Decimal Shift3Hrs { get; set; }
        public String Shift1Start { get; set; }
        public String Shift2Start { get; set; }
        public String Shift3Start { get; set; }
        public Decimal FirstWeekDay { get; set; }
        public String CanReceive1 { get; set; }
        public String CanReceive2 { get; set; }
        public String CanReceive3 { get; set; }
        public String CanReceive4 { get; set; }
        public String CanReceive5 { get; set; }
        public String CanReceive6 { get; set; }
        public String CanReceive7 { get; set; }
        public String CanShip1 { get; set; }
        public String CanShip2 { get; set; }
        public String CanShip3 { get; set; }
        public String CanShip4 { get; set; }
        public String CanShip5 { get; set; }
        public String CanShip6 { get; set; }
        public String CanShip7 { get; set; }
        public String IsHoliday1 { get; set; }
        public String IsHoliday2 { get; set; }
        public String IsHoliday3 { get; set; }
        public String IsHoliday4 { get; set; }
        public String IsHoliday5 { get; set; }
        public String IsHoliday6 { get; set; }
        public String IsHoliday7 { get; set; }
        public String HalfDay1 { get; set; }
        public String HalfDay2 { get; set; }
        public String HalfDay3 { get; set; }
        public String HalfDay4 { get; set; }
        public String HalfDay5 { get; set; }
        public String HalfDay6 { get; set; }
        public String HalfDay7 { get; set; }
        public DateTime CrevisedDate { get; set; }
        public String CrevisedBy { get; set; }
        public Decimal LogNoShip { get; set; }
        public Decimal LogNoDlry { get; set; }
        public Decimal LogNoMvmt { get; set; }
        public Decimal LogNoArOpen { get; set; }
        public Decimal LogNoApOpen { get; set; }
        public Decimal LogNoLedg { get; set; }
        public Decimal InvtCostAvail { get; set; }
        public Decimal InvtCostLdg { get; set; }
        public Decimal OnSalesCount { get; set; }
        public Decimal OnPurchCount { get; set; }
        public Decimal OnJobCount { get; set; }
        public Decimal ArInvoAmtBal { get; set; }
        public Decimal ArOpenAmtBal { get; set; }
        public Decimal ArNetAmtBal { get; set; }
        public Decimal ApInvoAmtBal { get; set; }
        public Decimal ApOpenAmtBal { get; set; }
        public Decimal ApNetAmtBal { get; set; }
        public String VerifySettings { get; set; }
        public String LogoBmp { get; set; }
        public String XconnectOn { get; set; }
        public String UloadPath { get; set; }
        public Decimal UloadBatchNo { get; set; }
        public String DloadPath { get; set; }
        public Decimal DloadBatchNo { get; set; }
        public Decimal DloadRecnum { get; set; }
        public String DloadCommand { get; set; }
        public String UloadCommand { get; set; }
        public String CompanyCode { get; set; }
        public String WithBtob { get; set; }
        public String WithIms { get; set; }
        public String LineNoEntry { get; set; }
        public String AcctItmSubcon { get; set; }
        public String WithAccpac { get; set; }
        public String AccpacIgrp { get; set; }
        public String SaleAnlysInt { get; set; }
        public String PurcAnlysInt { get; set; }
        public String ProdAnlysInt { get; set; }
        public String MvmtAnlysInt { get; set; }
        public String AnlysCat1 { get; set; }
        public String AnlysCat2 { get; set; }
        public String AnlysCat3 { get; set; }
        public String AnlysCat4 { get; set; }
        public String AnlysInt { get; set; }
        public Decimal ItmNoGridLen { get; set; }
        public Decimal BomNoGridLen { get; set; }
        public String EnableLot { get; set; }
        public String EnableSerial { get; set; }
        public Decimal LotNoLength { get; set; }
        public Decimal SerialNoLength { get; set; }
        public Decimal NextLotNo { get; set; }
        public Decimal NextSerialNo { get; set; }
        public Decimal MaxLotSize { get; set; }
        public String LotNoPrefix { get; set; }
        public String SerialNoPrefix { get; set; }
        public String WithLot { get; set; }
        public Decimal ItmNoLen { get; set; }
        public String RecordLock { get; set; }
        public String UserLog { get; set; }
        public Decimal ScalePrice { get; set; }
        public String NegStock { get; set; }
        public String WithSqlAttm { get; set; }
        public String WithResetLot { get; set; }
        public String WithResetSerial { get; set; }
        public DateTime PrevResetLotDate { get; set; }
        public DateTime PrevResetSerialDate { get; set; }
        public String AnlysCat5 { get; set; }
        public String AnlysCat6 { get; set; }
        public String AnlysCat7 { get; set; }
        public String AnlysCat8 { get; set; }
        public String AnlysCat9 { get; set; }
        public String AnlysCat10 { get; set; }
        public String CostSheetTabDescription1 { get; set; }
        public String CostSheetTabDescription2 { get; set; }
        public String CostSheetTabDescription3 { get; set; }
        public String CostSheetTabDescription4 { get; set; }
        public String CostSheetTabDescription5 { get; set; }
        public String CostSheetTabDescription6 { get; set; }
        public String CostSheetTabDescription7 { get; set; }
        public String AcctArTemp { get; set; }
        public String AcctApTemp { get; set; }
        public Boolean PlanOrdDefLastPoPrice { get; set; }
        public String PortalUrl { get; set; }
        public Decimal KayueNextPoNo { get; set; }
        public String LotNoUdfLabel01 { get; set; }
        public String LotNoUdfLabel02 { get; set; }
        public String LotNoUdfLabel03 { get; set; }
        public String LotNoUdfLabel04 { get; set; }
        public String LotNoUdfLabel05 { get; set; }
        public String BscPoOverBudgetPassword { get; set; }
        public String AcctArDeposit { get; set; }
        public String AcctApDeposit { get; set; }
        public String WithServerAttm { get; set; }
        public String FtpHost { get; set; }
        public String FtpUserId { get; set; }
        public String FtpPassword { get; set; }
        public String FtpNamePattern { get; set; }
        public String ImplementUomUppercase { get; set; }
        public String IntegratedEmailWithMsssageBox { get; set; }
        public String Cfg { get; set; }
    }
}